var KEY='basketball-library-v1',SID='basket-user',AID='basket-admin',route='home',filter='all',tab='videos',CODE='246810';
function seed(){return{cats:[{id:'c1',name:'运球',desc:'控球节奏与突破基本功'},{id:'c2',name:'投篮',desc:'建立稳定高效的投篮动作'},{id:'c3',name:'防守',desc:'脚步、站位与实战判断'},{id:'c4',name:'体能',desc:'速度、爆发与耐力提升'}],videos:[{id:'v1',title:'零基础控球：原地运球',cat:'c1',desc:'从手型、重心到节奏，掌握每天都能练的控球动作。',time:'08:42',free:true,pub:true},{id:'v2',title:'变向突破的三个关键细节',cat:'c1',desc:'学习实战中更有效的变向时机和启动动作。',time:'12:18',free:false,pub:true},{id:'v3',title:'投篮手型与发力顺序',cat:'c2',desc:'拆解完整投篮链条，让出手更稳定。',time:'10:26',free:true,pub:true},{id:'v4',title:'接球投篮脚步训练',cat:'c2',desc:'练习比赛常见场景中的脚步与出手衔接。',time:'14:05',free:false,pub:true},{id:'v5',title:'一对一防守站位',cat:'c3',desc:'掌握距离、重心与封堵方向。',time:'11:33',free:false,pub:true},{id:'v6',title:'篮球专项热身训练',cat:'c4',desc:'训练前的完整热身流程。',time:'07:15',free:true,pub:true}],users:[]}}
function db(){return JSON.parse(localStorage.getItem(KEY)||'null')||seed()}function save(x){localStorage.setItem(KEY,JSON.stringify(x))}function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}function user(x){return x.users.find(function(u){return u.id===localStorage.getItem(SID)})}function member(u){return u&&u.status==='active'&&new Date(u.until)>new Date()}function cat(x,id){var c=x.cats.find(function(y){return y.id===id});return c?c.name:'未分类'}function toast(t){var e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(function(){e.remove()},2200)}function modal(h){document.getElementById('pop').innerHTML='<div class="modalbg"><section class="modal">'+h+'</section></div>'}function closePop(){document.getElementById('pop').innerHTML=''}
function card(x,v){return '<article class="card" onclick="watch(\''+v.id+'\')"><div class="cover">🏀<span class="tag '+(v.free?'free':'')+'">'+(v.free?'免费试看':'会员专享')+'</span><span class="play">▶</span></div><div class="body"><small>'+cat(x,v.cat)+' · '+v.time+'</small><h3>'+v.title+'</h3><p>'+v.desc+'</p></div></article>'}function cards(x,vs){return '<div class="grid">'+vs.map(function(v){return card(x,v)}).join('')+'</div>'}
function home(x){return '<section class="hero"><div class="box heroGrid"><div><h1>把每一次训练<br>练得更明白</h1><p>系统篮球教学视频，覆盖控球、投篮、防守和体能训练。<br>跟着清晰步骤练习，让进步看得见。</p><button class="btn" onclick="go(\'courses\')">开始学习</button></div><div class="memberCard"><b>¥20 <small>/ 月</small></b><p>连续包月，随时可取消</p><p>✓ 完整观看全部教学视频</p><p>✓ 持续更新专项训练内容</p></div></div></section><section class="section"><div class="box"><div class="head"><div><h2>选择你的训练方向</h2><p class="muted">从基本功开始，找到适合你的内容。</p></div></div><div class="cats">'+x.cats.map(function(c){return '<button class="cat" onclick="choose(\''+c.id+'\')"><span class="ico">'+c.name[0]+'</span><b>'+c.name+'</b><span class="muted">'+c.desc+'</span></button>'}).join('')+'</div></div></section><section class="section"><div class="box"><h2>热门课程</h2><p class="muted">从精选内容开始你的本周训练。</p>'+cards(x,x.videos.filter(function(v){return v.pub}))+'</div></section>'}
function courses(x){var vs=x.videos.filter(function(v){return v.pub&&(filter==='all'||v.cat===filter)});return '<section class="section"><div class="box"><h2>全部训练课程</h2><p class="muted">按训练方向筛选，逐步打磨技术细节。</p><div class="filters"><button class="'+(filter==='all'?'on':'')+'" onclick="choose(\'all\')">全部</button>'+x.cats.map(function(c){return '<button class="'+(filter===c.id?'on':'')+'" onclick="choose(\''+c.id+'\')">'+c.name+'</button>'}).join('')+'</div>'+cards(x,vs)+'</div></section>'}
function membership(x){var u=user(x),on=member(u);return '<section class="section"><div class="box two"><div class="panel"><p class="muted">MEMBERSHIP</p><h2>训练库连续包月会员</h2><div class="price">¥20 <small>/ 月</small></div><ul class="list"><li>解锁所有会员专属教学视频</li><li>每月自动续费，演示环境可取消</li><li>持续获得新增训练课程</li></ul><button class="btn" onclick="activate()">'+(on?'会员已开通':'模拟微信签约并开通')+'</button><p class="muted">本机演示不会产生真实扣款。</p></div><div class="panel"><h3>我的会员状态</h3><h2>'+(u?(on?'训练库会员':'普通用户'):'尚未登录')+'</h2><p class="muted">'+(on?'有效期至 '+new Date(u.until).toLocaleDateString():'开通会员后即可观看全部课程。')+'</p>'+(on?'<button class="btn alt" onclick="cancelMine()">取消自动续费</button>':'<button class="btn alt" onclick="login()">手机号登录</button>')+'</div></div></section>'}
function profile(x){var u=user(x);return '<section class="section"><div class="box">'+(u?'<div class="panel"><h2>个人中心</h2><p class="muted">登录手机号</p><h3>'+u.phone+'</h3><p class="muted">'+(member(u)?'会员有效期至 '+new Date(u.until).toLocaleDateString():'当前为普通用户')+'</p><button class="btn alt" onclick="logout()">退出登录</button></div>':'<div class="panel"><h2>登录后查看个人中心</h2><button class="btn" onclick="login()">立即登录</button></div>')+'</div></section>'}
function render(){var x=db();document.getElementById('app').innerHTML=route==='courses'?courses(x):route==='membership'?membership(x):route==='profile'?profile(x):route==='admin'?admin(x):home(x);document.getElementById('account').textContent=user(x)?'个人中心':'登录';scrollTo(0,0)}function go(r){route=r;render()}function choose(c){filter=c;route='courses';render()}function account(){user(db())?go('profile'):login()}
function login(){modal('<div class="modalhead"><h3>手机号登录</h3><button class="close" onclick="closePop()">×</button></div><form class="form" onsubmit="doLogin(event)"><label>手机号码<input name="phone" required pattern="1[3-9][0-9]{9}" placeholder="请输入 11 位手机号"></label><button type="button" class="btn alt" onclick="sendCode()">发送验证码</button><div class="code" id="code">点击发送验证码</div><label>验证码<input name="code" required></label><button class="btn">登录 / 注册</button></form>')}function sendCode(){document.getElementById('code').textContent='演示验证码：'+CODE}function doLogin(e){e.preventDefault();var f=new FormData(e.target);if(f.get('code')!==CODE)return toast('验证码错误');var x=db(),u=x.users.find(function(a){return a.phone===f.get('phone')});if(!u){u={id:uid(),phone:f.get('phone'),status:'inactive'};x.users.push(u);save(x)}localStorage.setItem(SID,u.id);closePop();toast('登录成功');render()}function logout(){localStorage.removeItem(SID);go('home')}function activate(){var x=db(),u=user(x);if(!u)return login();u.status='active';u.auto=true;u.until=new Date(Math.max(Date.now(),new Date(u.until||0).getTime())+2592000000).toISOString();save(x);toast('模拟签约成功，会员已开通');render()}function cancelMine(){var x=db(),u=user(x);u.auto=false;save(x);toast('已取消自动续费，权益保留至到期');render()}function watch(id){var x=db(),v=x.videos.find(function(a){return a.id===id});if(!v.free&&!member(user(x)))return modal('<div class="modalhead"><h3>会员专享课程</h3><button class="close" onclick="closePop()">×</button></div><p class="muted">开通会员即可观看全部教学视频。</p><button class="btn" onclick="closePop();go(\'membership\')">¥20 / 月，立即开通</button>');modal('<div class="modalhead"><h3>'+v.title+'</h3><button class="close" onclick="closePop()">×</button></div><div class="cover">🏀</div><p class="muted">'+v.desc+'</p><p class="muted">演示课程尚未上传视频，正式版将在此播放教学内容。</p>')}
function adminEntry(){if(sessionStorage.getItem(AID))return go('admin');modal('<div class="modalhead"><h3>管理员登录</h3><button class="close" onclick="closePop()">×</button></div><p class="muted">演示账号：admin / admin123</p><form class="form" onsubmit="adminLogin(event)"><input name="user" value="admin"><input name="pass" type="password" value="admin123"><button class="btn">进入后台</button></form>')}function adminLogin(e){e.preventDefault();var f=new FormData(e.target);if(f.get('user')!=='admin'||f.get('pass')!=='admin123')return toast('账号或密码错误');sessionStorage.setItem(AID,'1');closePop();go('admin')}function admin(x){if(!sessionStorage.getItem(AID)){setTimeout(adminEntry);return home(x)}return '<div class="admin"><aside><button onclick="tab=\'videos\';render()">课程管理</button><button onclick="tab=\'cats\';render()">分类管理</button><button onclick="tab=\'users\';render()">用户会员</button><button onclick="sessionStorage.removeItem(AID);go(\'home\')">退出后台</button></aside><div class="content">'+adminBody(x)+'</div></div>'}
function adminBody(x){if(tab==='cats')return '<div class="head"><h2>分类管理</h2><button class="btn small" onclick="addCat()">新增分类</button></div><div class="table"><table>'+x.cats.map(function(c){return '<tr><td>'+c.name+'</td><td>'+c.desc+'</td><td><button class="act red" onclick="delCat(\''+c.id+'\')">删除</button></td></tr>'}).join('')+'</table></div>';if(tab==='users')return '<h2>用户会员</h2><div class="table"><table><tr><th>手机号</th><th>状态</th><th>到期</th><th>操作</th></tr>'+x.users.map(function(u){return '<tr><td>'+u.phone+'</td><td>'+(member(u)?'有效会员':'普通用户')+'</td><td>'+(u.until?new Date(u.until).toLocaleDateString():'无')+'</td><td><button class="act" onclick="extend(\''+u.id+'\')">续期30天</button><button class="act red" onclick="stop(\''+u.id+'\')">取消</button></td></tr>'}).join('')+'</table></div>';return '<div class="head"><h2>课程管理</h2><button class="btn small" onclick="addVideo()">新增课程</button></div><div class="table"><table><tr><th>课程</th><th>分类</th><th>权限</th><th>状态</th><th>操作</th></tr>'+x.videos.map(function(v){return '<tr><td>'+v.title+'</td><td>'+cat(x,v.cat)+'</td><td>'+(v.free?'免费试看':'会员专享')+'</td><td>'+(v.pub?'已发布':'未发布')+'</td><td><button class="act red" onclick="delVideo(\''+v.id+'\')">删除</button></td></tr>'}).join('')+'</table></div>'}
function addCat(){var n=prompt('分类名称');if(!n)return;var x=db();x.cats.push({id:uid(),name:n,desc:prompt('简短介绍')||''});save(x);render()}function delCat(id){var x=db();if(x.videos.some(function(v){return v.cat===id}))return toast('请先删除该分类下课程');x.cats=x.cats.filter(function(c){return c.id!==id});save(x);render()}function addVideo(){var x=db(),title=prompt('课程标题');if(!title)return;var names=x.cats.map(function(c,i){return(i+1)+'. '+c.name}).join('\n'),pick=parseInt(prompt('选择分类：\n'+names)||'1')-1;x.videos.push({id:uid(),title:title,cat:(x.cats[pick]||x.cats[0]).id,desc:prompt('课程简介')||'',time:prompt('课程时长，例如 10:30')||'10:00',free:confirm('设为免费试看？'),pub:true});save(x);render()}function delVideo(id){if(!confirm('确定删除课程吗？'))return;var x=db();x.videos=x.videos.filter(function(v){return v.id!==id});save(x);render()}function extend(id){var x=db(),u=x.users.find(function(a){return a.id===id});u.status='active';u.until=new Date(Math.max(Date.now(),new Date(u.until||0).getTime())+2592000000).toISOString();save(x);render()}function stop(id){var x=db(),u=x.users.find(function(a){return a.id===id});u.status='cancelled';u.until=null;save(x);render()}
save(db());render();

/* Enhanced local media management. Later declarations intentionally replace the basic demo handlers above. */
function card(x,v){return '<a class="card" href="course.html?id='+encodeURIComponent(v.id)+'"><div class="cover">'+(v.cover?'<img src="'+v.cover+'" style="width:100%;height:100%;object-fit:cover">':'🏀')+'<span class="tag '+(v.free?'free':'')+'">'+(v.free?'免费试看':'会员专享')+'</span><span class="play">▶</span></div><div class="body"><small>'+cat(x,v.cat)+' · '+v.time+'</small><h3>'+v.title+'</h3><p>'+v.desc+'</p></div></a>'}
function adminBody(x){if(tab==='cats')return '<div class="head"><h2>分类管理</h2><button class="btn small" onclick="addCat()">新增分类</button></div><div class="table"><table>'+x.cats.map(function(c){return '<tr><td>'+c.name+'</td><td>'+c.desc+'</td><td><button class="act red" onclick="delCat(\''+c.id+'\')">删除</button></td></tr>'}).join('')+'</table></div>';if(tab==='users')return '<h2>用户会员</h2><div class="table"><table><tr><th>手机号</th><th>状态</th><th>到期</th><th>操作</th></tr>'+x.users.map(function(u){return '<tr><td>'+u.phone+'</td><td>'+(member(u)?'有效会员':'普通用户')+'</td><td>'+(u.until?new Date(u.until).toLocaleDateString():'无')+'</td><td><button class="act" onclick="extend(\''+u.id+'\')">续期30天</button><button class="act red" onclick="stop(\''+u.id+'\')">取消</button></td></tr>'}).join('')+'</table></div>';return '<div class="head"><div><h2>课程管理</h2><p class="muted">视频保存在当前浏览器的本机存储中。</p></div><button class="btn small" onclick="addVideo()">新增课程</button></div><div class="table"><table><tr><th>课程</th><th>分类</th><th>权限</th><th>状态</th><th>操作</th></tr>'+x.videos.map(function(v){return '<tr><td>'+v.title+'</td><td>'+cat(x,v.cat)+'</td><td>'+(v.free?'免费试看':'会员专享')+'</td><td>'+(v.pub?'已发布':'未发布')+'</td><td><button class="act" onclick="editVideo(\''+v.id+'\')">编辑</button><button class="act red" onclick="delVideo(\''+v.id+'\')">删除</button></td></tr>'}).join('')+'</table></div>'}
function addVideo(){videoForm('')}function editVideo(id){videoForm(id)}
function videoForm(id){var x=db(),v=x.videos.find(function(a){return a.id===id})||{};modal('<div class="modalhead"><h3>'+(id?'编辑':'新增')+'课程</h3><button class="close" onclick="closePop()">×</button></div><form class="form" onsubmit="saveVideo(event,\''+id+'\')"><label>课程标题<input name="title" required value="'+(v.title||'')+'"></label><label>训练分类<select name="cat">'+x.cats.map(function(c){return '<option value="'+c.id+'" '+(v.cat===c.id?'selected':'')+'>'+c.name+'</option>'}).join('')+'</select></label><label>课程时长<input name="time" required value="'+(v.time||'10:00')+'"></label><label>课程简介<textarea name="desc" required>'+(v.desc||'')+'</textarea></label><label>封面图片<input name="cover" type="file" accept="image/png,image/jpeg,image/webp"></label><label>教学视频<input name="video" type="file" accept="video/mp4,video/webm,video/ogg"></label><label><span><input name="free" type="checkbox" '+(v.free?'checked':'')+'> 免费试看</span></label><label><span><input name="pub" type="checkbox" '+(v.pub!==false?'checked':'')+'> 发布课程</span></label><p class="muted">视频最大 200MB，支持 MP4、WebM、OGG。</p><button class="btn">保存课程</button></form>')}
function fileURL(f){return new Promise(function(ok){var r=new FileReader();r.onload=function(){ok(r.result)};r.readAsDataURL(f)})}
function mediaDB(){return new Promise(function(ok,bad){var q=indexedDB.open('basketball-media',1);q.onupgradeneeded=function(){q.result.createObjectStore('media')};q.onsuccess=function(){ok(q.result)};q.onerror=function(){bad(q.error)}})}
function putMedia(k,v){return mediaDB().then(function(d){return new Promise(function(ok,bad){var t=d.transaction('media','readwrite');t.objectStore('media').put(v,k);t.oncomplete=ok;t.onerror=function(){bad(t.error)}})})}
function getMedia(k){return mediaDB().then(function(d){return new Promise(function(ok,bad){var q=d.transaction('media').objectStore('media').get(k);q.onsuccess=function(){ok(q.result)};q.onerror=function(){bad(q.error)}})})}
async function saveVideo(e,id){e.preventDefault();var x=db(),f=new FormData(e.target),video=f.get('video'),cover=f.get('cover'),v=x.videos.find(function(a){return a.id===id});if(video.size>209715200)return toast('视频不能超过 200MB');if(video.size&&['video/mp4','video/webm','video/ogg'].indexOf(video.type)<0)return toast('视频格式不支持');if(!v){v={id:uid()};x.videos.push(v)}v.title=f.get('title');v.cat=f.get('cat');v.time=f.get('time');v.desc=f.get('desc');v.free=f.get('free')==='on';v.pub=f.get('pub')==='on';if(cover.size)v.cover=await fileURL(cover);if(video.size){v.blob='media-'+v.id;await putMedia(v.blob,video)}save(x);closePop();toast('课程已保存');render()}
async function watch(id){var x=db(),v=x.videos.find(function(a){return a.id===id});if(!v.pub)return toast('课程暂未发布');if(!v.free&&!member(user(x)))return modal('<div class="modalhead"><h3>会员专享课程</h3><button class="close" onclick="closePop()">×</button></div><p class="muted">开通会员即可观看全部教学视频。</p><button class="btn" onclick="closePop();go(\'membership\')">¥20 / 月，立即开通</button>');var src='';if(v.blob){var f=await getMedia(v.blob);if(f)src=URL.createObjectURL(f)}modal('<div class="modalhead"><h3>'+v.title+'</h3><button class="close" onclick="closePop()">×</button></div>'+(src?'<video controls autoplay style="width:100%;background:#102448" src="'+src+'"></video>':'<div class="cover">🏀</div><p class="muted">该演示课程尚未上传视频，可在管理后台添加本机视频。</p>')+'<p class="muted">'+v.desc+'</p>')}

function watch(id){window.location.href='course.html?id='+encodeURIComponent(id)}

/* Dual-version course workflow: original video is free; translated subtitle video is VIP. */
function videoForm(id){var x=db(),v=x.videos.find(function(a){return a.id===id})||{};modal('<div class="modalhead"><h3>'+(id?'编辑':'新增')+'课程</h3><button class="close" onclick="closePop()">×</button></div><form class="form" onsubmit="saveVideo(event,\''+id+'\')"><label>课程标题<input name="title" required value="'+(v.title||'')+'"></label><label>训练分类<select name="cat">'+x.cats.map(function(c){return '<option value="'+c.id+'" '+(v.cat===c.id?'selected':'')+'>'+c.name+'</option>'}).join('')+'</select></label><label>课程时长<input name="time" required value="'+(v.time||'10:00')+'"></label><label>课程简介<textarea name="desc" required>'+(v.desc||'')+'</textarea></label><label>封面图片<input name="cover" type="file" accept="image/png,image/jpeg,image/webp"></label><label>无翻译原版视频（免费）<input name="originalVideo" type="file" accept="video/mp4,video/webm,video/ogg"></label><label>中文字幕翻译版视频（VIP）<input name="translatedVideo" type="file" accept="video/mp4,video/webm,video/ogg"></label><label><span><input name="pub" type="checkbox" '+(v.pub!==false?'checked':'')+'> 发布课程</span></label><p class="muted">原版视频所有用户免费看；字幕翻译版仅会员可看。会员费收取的是翻译、字幕制作、校对和资料整理服务费。</p><button class="btn">保存课程</button></form>')}
async function saveVideo(e,id){e.preventDefault();var x=db(),f=new FormData(e.target),original=f.get('originalVideo'),translated=f.get('translatedVideo'),cover=f.get('cover'),v=x.videos.find(function(a){return a.id===id});function invalid(file){return file.size&&['video/mp4','video/webm','video/ogg'].indexOf(file.type)<0}if(original.size>209715200||translated.size>209715200)return toast('视频不能超过 200MB');if(invalid(original)||invalid(translated))return toast('视频格式不支持');if(!v){v={id:uid()};x.videos.push(v)}v.title=f.get('title');v.cat=f.get('cat');v.time=f.get('time');v.desc=f.get('desc');v.free=true;v.pub=f.get('pub')==='on';if(cover.size)v.cover=await fileURL(cover);if(original.size){v.originalBlob='original-'+v.id;await putMedia(v.originalBlob,original)}if(translated.size){v.translatedBlob='translated-'+v.id;await putMedia(v.translatedBlob,translated)}save(x);closePop();toast('课程已保存：原版免费，字幕版VIP');render()}
function membership(x){var u=user(x),on=member(u);return '<section class="section"><div class="box two"><div class="panel"><p class="muted">TRANSLATION SERVICE</p><h2>字幕翻译服务会员</h2><div class="price">¥20 <small>/ 月</small></div><ul class="list"><li>原版无翻译视频永久免费</li><li>会员可观看中文字幕翻译版</li><li>费用用于翻译、字幕制作、校对和学习资料整理</li></ul><button class="btn" onclick="activate()">'+(on?'会员已开通':'模拟微信签约并开通')+'</button><p class="muted">声明：会员费收取的是翻译服务费，不是原版视频观看费。本机演示不会产生真实扣款。</p></div><div class="panel"><h3>我的会员状态</h3><h2>'+(u?(on?'翻译服务会员':'普通用户'):'尚未登录')+'</h2><p class="muted">'+(on?'可观看字幕翻译版，有效期至 '+new Date(u.until).toLocaleDateString():'原版视频免费；开通后可看字幕翻译版。')+'</p>'+(on?'<button class="btn alt" onclick="cancelMine()">取消自动续费</button>':'<button class="btn alt" onclick="login()">手机号登录</button>')+'</div></div></section>'}

/* Email login workflow. Demo code is still shown on screen; production should send it by email. */
function userLabel(u){return u?(u.email||u.phone||'未填写邮箱'):''}
function login(){modal('<div class="modalhead"><h3>邮箱登录</h3><button class="close" onclick="closePop()">×</button></div><form class="form" onsubmit="doLogin(event)"><label>邮箱地址<input name="email" type="email" required placeholder="请输入邮箱地址"></label><button type="button" class="btn alt" onclick="sendCode()">发送邮箱验证码</button><div class="code" id="code">点击发送验证码</div><label>验证码<input name="code" required></label><button class="btn">登录 / 注册</button></form>')}
function sendCode(){document.getElementById('code').textContent='演示邮箱验证码：'+CODE}
function doLogin(e){e.preventDefault();var f=new FormData(e.target);if(f.get('code')!==CODE)return toast('验证码错误');var x=db(),email=String(f.get('email')||'').trim().toLowerCase(),u=x.users.find(function(a){return a.email===email});if(!u){u={id:uid(),email:email,status:'inactive'};x.users.push(u);save(x)}localStorage.setItem(SID,u.id);closePop();toast('邮箱登录成功');render()}
function profile(x){var u=user(x);return '<section class="section"><div class="box">'+(u?'<div class="panel"><h2>个人中心</h2><p class="muted">登录邮箱</p><h3>'+userLabel(u)+'</h3><p class="muted">'+(member(u)?'翻译服务会员有效期至 '+new Date(u.until).toLocaleDateString():'当前为普通用户，原版视频可免费看')+'</p><button class="btn alt" onclick="logout()">退出登录</button></div>':'<div class="panel"><h2>登录后查看个人中心</h2><button class="btn" onclick="login()">邮箱登录</button></div>')+'</div></section>'}
function membership(x){var u=user(x),on=member(u);return '<section class="section"><div class="box two"><div class="panel"><p class="muted">TRANSLATION SERVICE</p><h2>字幕翻译服务会员</h2><div class="price">¥20 <small>/ 月</small></div><ul class="list"><li>原版无翻译视频永久免费</li><li>会员可观看中文字幕翻译版</li><li>费用用于翻译、字幕制作、校对和学习资料整理</li></ul><button class="btn" onclick="activate()">'+(on?'会员已开通':'模拟微信签约并开通')+'</button><p class="muted">声明：会员费收取的是翻译服务费，不是原版视频观看费。本机演示不会产生真实扣款。</p></div><div class="panel"><h3>我的会员状态</h3><h2>'+(u?(on?'翻译服务会员':'普通用户'):'尚未登录')+'</h2><p class="muted">'+(on?'可观看字幕翻译版，有效期至 '+new Date(u.until).toLocaleDateString():'原版视频免费；开通后可看字幕翻译版。')+'</p>'+(u?'<p class="muted">登录邮箱：'+userLabel(u)+'</p>':'')+(on?'<button class="btn alt" onclick="cancelMine()">取消自动续费</button>':'<button class="btn alt" onclick="login()">邮箱登录</button>')+'</div></div></section>'}
function adminBody(x){if(tab==='cats')return '<div class="head"><h2>分类管理</h2><button class="btn small" onclick="addCat()">新增分类</button></div><div class="table"><table>'+x.cats.map(function(c){return '<tr><td>'+c.name+'</td><td>'+c.desc+'</td><td><button class="act red" onclick="delCat(\''+c.id+'\')">删除</button></td></tr>'}).join('')+'</table></div>';if(tab==='users')return '<h2>用户会员</h2><div class="table"><table><tr><th>邮箱</th><th>状态</th><th>到期</th><th>操作</th></tr>'+x.users.map(function(u){return '<tr><td>'+userLabel(u)+'</td><td>'+(member(u)?'有效会员':'普通用户')+'</td><td>'+(u.until?new Date(u.until).toLocaleDateString():'无')+'</td><td><button class="act" onclick="extend(\''+u.id+'\')">续期30天</button><button class="act red" onclick="stop(\''+u.id+'\')">取消</button></td></tr>'}).join('')+'</table></div>';return '<div class="head"><div><h2>课程管理</h2><p class="muted">视频保存在当前浏览器的本机存储中。</p></div><button class="btn small" onclick="addVideo()">新增课程</button></div><div class="table"><table><tr><th>课程</th><th>分类</th><th>版本规则</th><th>状态</th><th>操作</th></tr>'+x.videos.map(function(v){return '<tr><td>'+v.title+'</td><td>'+cat(x,v.cat)+'</td><td>原版免费 / 字幕VIP</td><td>'+(v.pub?'已发布':'未发布')+'</td><td><button class="act" onclick="editVideo(\''+v.id+'\')">编辑</button><button class="act red" onclick="delVideo(\''+v.id+'\')">删除</button></td></tr>'}).join('')+'</table></div>'}

/* Production email code flow. On file:// it falls back to the visible demo code. */
function isLocalDemo(){return location.protocol==='file:'}
function login(){modal('<div class="modalhead"><h3>邮箱登录</h3><button class="close" onclick="closePop()">×</button></div><form class="form" onsubmit="doLogin(event)"><label>邮箱地址<input name="email" type="email" required placeholder="请输入邮箱地址"></label><input name="challenge" type="hidden"><button type="button" class="btn alt" onclick="sendCode()">发送邮箱验证码</button><div class="code" id="code">点击发送验证码</div><label>验证码<input name="code" required placeholder="请输入邮箱收到的 6 位验证码"></label><button class="btn">登录 / 注册</button></form>')}
async function sendCode(){var form=document.querySelector('#pop form'),email=String(form.email.value||'').trim().toLowerCase(),box=document.getElementById('code');if(!email)return toast('请先输入邮箱');if(isLocalDemo()){box.textContent='本地演示验证码：'+CODE;return}box.textContent='正在发送验证码...';try{var res=await fetch('/api/send-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email})});var data=await res.json();if(!res.ok)throw new Error(data.error||'发送失败');form.challenge.value=data.challenge;box.textContent='验证码已发送到邮箱，请查收';toast('验证码已发送')}catch(err){box.textContent='发送失败';toast(err.message||'发送失败')}}
async function doLogin(e){e.preventDefault();var f=new FormData(e.target),email=String(f.get('email')||'').trim().toLowerCase(),code=String(f.get('code')||'').trim();if(isLocalDemo()){if(code!==CODE)return toast('验证码错误');return finishEmailLogin(email)}try{var res=await fetch('/api/verify-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email,code:code,challenge:f.get('challenge')})});var data=await res.json();if(!res.ok)throw new Error(data.error||'验证码错误');finishEmailLogin(email)}catch(err){toast(err.message||'验证码错误')}}
function finishEmailLogin(email){var x=db(),u=x.users.find(function(a){return a.email===email});if(!u){u={id:uid(),email:email,status:'inactive'};x.users.push(u)}save(x);localStorage.setItem(SID,u.id);closePop();toast('邮箱登录成功');render()}
