/* Catalog storefront layer: keeps membership and admin behavior from app.js. */
(function(){
var x=db(), changed=false;
var moreCats=[['c5','进攻技巧','终结、脚步与个人进攻'],['c6','团队战术','配合、跑位与比赛阅读'],['c7','教练专区','训练设计与执教方法'],['c8','青少年训练','适合初学者的成长课程']];
moreCats.forEach(function(c){if(!x.cats.some(function(y){return y.id===c[0]})){x.cats.push({id:c[0],name:c[1],desc:c[2]});changed=true}});
var moreVideos=[
{id:'v7',title:'篮下终结：弱侧手上篮训练',cat:'c5',desc:'提升对抗后的篮下终结稳定性。',time:'16:20',free:false,pub:true,coach:'张教练',rating:5,img:'https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=700&q=80'},
{id:'v8',title:'挡拆进攻基础：阅读防守选择',cat:'c6',desc:'拆解持球人和掩护人的判断要点。',time:'21:45',free:false,pub:true,coach:'李教练',rating:5,img:'https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&w=700&q=80'},
{id:'v9',title:'赛季前体能训练计划',cat:'c4',desc:'建立适合篮球运动的爆发力与耐力。',time:'18:10',free:false,pub:true,coach:'王体能教练',rating:4,img:'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?auto=format&fit=crop&w=700&q=80'},
{id:'v10',title:'青少年训练课：基础脚步游戏',cat:'c8',desc:'让初学者在趣味练习中建立动作基础。',time:'13:28',free:true,pub:true,coach:'陈教练',rating:5,img:'https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&w=700&q=80'},
{id:'v11',title:'训练课设计：90 分钟完整模板',cat:'c7',desc:'帮助教练组织更高效的团队训练。',time:'25:30',free:false,pub:true,coach:'教练团队',rating:5,img:'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=700&q=80'},
{id:'v12',title:'外线防守：逼迫持球人走弱侧',cat:'c3',desc:'学习压迫、防突破和协防沟通。',time:'17:36',free:false,pub:true,coach:'刘教练',rating:4,img:'https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=700&q=80'}];
var basicImgs=['https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?auto=format&fit=crop&w=700&q=80'];
x.videos.forEach(function(v,i){if(!v.img){v.img=basicImgs[i%basicImgs.length];changed=true}if(!v.coach){v.coach=['训练库教练组','周教练','林教练'][i%3];changed=true}if(!v.rating){v.rating=4+(i%2);changed=true}});
moreVideos.forEach(function(v){if(!x.videos.some(function(y){return y.id===v.id})){x.videos.push(v);changed=true}});if(changed)save(x);
})();
function stars(n){return '★★★★★'.slice(0,n)+'☆☆☆☆☆'.slice(n)}
function productCard(x,v){var img=v.cover||v.img||'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=700&q=80';var href='course.html?id='+encodeURIComponent(v.id);return '<a class="product" href="'+href+'"><div class="product-cover cover-'+v.cat+'"><img src="'+img+'" alt="" onerror="this.remove()"><span class="access free">原版免费</span><span class="access subtitle">字幕VIP</span></div><div class="product-body"><div class="product-kicker">'+cat(x,v.cat)+'</div><h3>'+v.title+'</h3><div class="coach">主讲：'+(v.coach||'训练库教练组')+' · '+v.time+'</div><div class="stars">'+stars(v.rating||5)+'</div><div class="product-foot"><b>翻译服务 ¥20 / 月</b><span>立即学习 ›</span></div></div></a>'}
function productGrid(x,vs,cls){return vs.length?'<div class="products '+(cls||'')+'">'+vs.map(function(v){return productCard(x,v)}).join('')+'</div>':'<div class="no-results">暂时没有符合条件的课程。</div>'}
function shelf(x,title,vs){return '<section class="store-section"><div class="box"><div class="shelf-head"><h2>'+title+'</h2><button onclick="go(\'courses\')">查看全部 ›</button></div>'+productGrid(x,vs.slice(0,4))+'</div></section>'}
function menu(x){return '<div class="catalog-menu"><div class="catalog-title">篮球教学分类</div>'+x.cats.map(function(c){return '<button onclick="choose(\''+c.id+'\')"><span>'+c.name+'</span><b>›</b></button>'}).join('')+'</div>'}
function home(x){var vs=x.videos.filter(function(v){return v.pub});return '<section class="store-hero"><div class="box store-layout">'+menu(x)+'<div><div class="feature-banner"><p>篮球训练库 · 专业教学资源</p><h1>让训练更系统<br>让每一步进步都有方法</h1><p>原版教学视频免费看；中文字幕翻译版为会员服务。</p><button class="btn orange" onclick="go(\'membership\')">开通翻译服务 ¥20 / 月</button></div><div class="benefitbar"><div><b>原版免费</b>无翻译原视频可直接看</div><div><b>字幕翻译</b>会员观看中文字幕版</div><div><b>持续更新</b>每周新增教学内容</div><div><b>费用声明</b>会员费收的是翻译服务费</div></div></div></div></section><section class="store-section white"><div class="box"><div class="shelf-head"><h2>按训练方向浏览</h2></div><div class="directory">'+x.cats.map(function(c){return '<button class="dir-item" onclick="choose(\''+c.id+'\')"><b>'+c.name+'</b><span>'+c.desc+'</span></button>'}).join('')+'</div></div></section>'+shelf(x,'最新上线课程',vs.slice().reverse())+shelf(x,'热门训练课程',vs.slice(0,4))+shelf(x,'高评分推荐',vs.slice().sort(function(a,b){return (b.rating||0)-(a.rating||0)}))+'<section class="store-section"><div class="box membership-strip"><div class="membership-strip-inner"><div><h2>字幕翻译服务会员：每月 ¥20</h2><p>原版视频免费，会员费仅用于中文字幕翻译、校对和学习资料整理服务。</p></div><button class="btn orange" onclick="go(\'membership\')">立即开通翻译服务</button></div></div></section>'}
var searchTerm='';
function quickSearch(e){e.preventDefault();searchTerm=document.getElementById('site-search').value.trim();filter='all';route='courses';render()}
function courses(x){var vs=x.videos.filter(function(v){return v.pub&&(filter==='all'||v.cat===filter)&&(!searchTerm||(v.title+v.desc+cat(x,v.cat)).indexOf(searchTerm)>=0)});return '<section class="course-page"><div class="box course-shell"><aside class="sidebox"><h3>篮球教学分类</h3><button class="'+(filter==='all'?'on':'')+'" onclick="choose(\'all\')">全部课程</button>'+x.cats.map(function(c){return '<button class="'+(filter===c.id?'on':'')+'" onclick="choose(\''+c.id+'\')">'+c.name+'</button>'}).join('')+'</aside><div><div class="result-title"><div><p class="muted">BASKETBALL TRAINING VIDEOS</p><h2>'+(searchTerm?'搜索：'+searchTerm:(filter==='all'?'全部篮球课程':cat(x,filter)))+'</h2></div><span>共 '+vs.length+' 节课程</span></div><div class="filters"><button class="'+(filter==='all'?'on':'')+'" onclick="choose(\'all\')">全部</button>'+x.cats.map(function(c){return '<button class="'+(filter===c.id?'on':'')+'" onclick="choose(\''+c.id+'\')">'+c.name+'</button>'}).join('')+'</div>'+productGrid(x,vs,'result-grid')+'</div></div></section>'}
function choose(c){filter=c;searchTerm='';route='courses';render()}
function openCoursePage(id){window.location.href='course.html?id='+encodeURIComponent(id)}
function watch(id){openCoursePage(id)}
render();

